# Generated by Django 6.0.1 on 2026-04-01 07:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=50)),
                ('primary_branch', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriageAssessment',
            fields=[
                ('triage_id', models.AutoField(primary_key=True, serialize=False)),
                ('triage_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('complaint', models.TextField()),
                ('pain_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'title__in': ['Doctor', 'MD', 'DO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patients', to='website.staff')),
                ('nurse', models.ForeignKey(blank=True, limit_choices_to={'title__in': ['Nurse', 'RN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_patients', to='website.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Triage_scores',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('esi_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('resources_needed', models.TextField()),
                ('triage', models.ForeignKey(db_column='triage_id', on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='website.triageassessment')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exiting_time', models.DateTimeField(blank=True, null=True)),
                ('waiting_time', models.DurationField(blank=True, editable=False, null=True)),
                ('queue_count_before_processing', models.IntegerField(default=0, editable=False)),
                ('queue_count_after_processing', models.IntegerField(default=0, editable=False)),
                ('queue_difference', models.IntegerField(editable=False, null=True)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='website.patient')),
            ],
        ),
        migrations.AddField(
            model_name='triageassessment',
            name='visit',
            field=models.ForeignKey(db_column='visit_id', on_delete=django.db.models.deletion.CASCADE, related_name='triage_assessments', to='website.visit'),
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('Vitals_id', models.AutoField(primary_key=True, serialize=False)),
                ('Age', models.IntegerField()),
                ('Heart_rate', models.IntegerField()),
                ('Systolic_blood_pressure', models.IntegerField()),
                ('Oxygen_saturation', models.IntegerField()),
                ('Body_temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Pain_level', models.IntegerField()),
                ('Chronic_disease_count', models.IntegerField()),
                ('Time_of_vitals', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(db_column='visit_id', on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='website.visit')),
            ],
            options={
                'verbose_name_plural': 'Vitals',
                'ordering': ['Time_of_vitals'],
            },
        ),
        migrations.AddField(
            model_name='triageassessment',
            name='vitals',
            field=models.ForeignKey(db_column='vitals_id', on_delete=django.db.models.deletion.CASCADE, related_name='triage_assessments', to='website.vitals'),
        ),
    ]
