# Generated by Django 6.0.1 on 2026-04-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triage_scores',
            old_name='triage',
            new_name='triage_id',
        ),
        migrations.RenameField(
            model_name='triageassessment',
            old_name='visit',
            new_name='visit_id',
        ),
        migrations.RenameField(
            model_name='triageassessment',
            old_name='vitals',
            new_name='vitals_id',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='vitals',
            old_name='visit',
            new_name='visit_id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, null=True),
        ),
    ]
