# Generated by Django 6.0.1 on 2026-04-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_triage_triage_scores_triage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='Body_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, default=96.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='Chronic_disease_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='Heart_rate',
            field=models.IntegerField(blank=True, default=61),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='Oxygen_saturation',
            field=models.IntegerField(blank=True, default=91),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='Pain_level',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='Systolic_blood_pressure',
            field=models.IntegerField(blank=True, default=101),
        ),
    ]
