# Generated by Django 6.0.1 on 2026-04-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_vitals_age_alter_vitals_body_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='Age',
            field=models.IntegerField(blank=True, default=35),
        ),
    ]
