# Generated by Django 6.0.1 on 2026-04-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_vitals_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='diff_resources',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='disoriented',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='high_risk',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='life_saving_intervention',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='severe_pain',
            field=models.IntegerField(null=True),
        ),
    ]
