# Generated by Django 6.0.1 on 2026-04-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_vitals_respiratory_rate_alter_vitals_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='complaint',
            field=models.CharField(blank=True, null=True),
        ),
    ]
