# Generated by Django 6.0.1 on 2026-04-14 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_visit_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triageassessment',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='triageassessment',
            name='pain_score',
        ),
        migrations.RemoveField(
            model_name='triageassessment',
            name='visit_id',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='waiting_time',
        ),
        migrations.AddField(
            model_name='triageassessment',
            name='esi_level',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Triage_scores',
        ),
    ]
