# Generated by Django 6.0.1 on 2026-04-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_triageassessment_complaint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(blank=True, choices=[('A', 'a'), ('B', 'b'), ('C', 'c')], max_length=6, null=True)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
