# Generated by Django 6.0.1 on 2026-04-20 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='shift_id',
            field=models.ForeignKey(db_column='shift_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shift', to='website.shift'),
        ),
    ]
