# Generated by Django 6.0.1 on 2026-04-20 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_staff_shift_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='primary_branch',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='title',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='queue_count_after_processing',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='queue_count_before_processing',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='queue_difference',
        ),
        migrations.AlterField(
            model_name='patient',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_patients', to='website.staff'),
        ),
    ]
