# Generated by Django 6.0.1 on 2026-04-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_patient_doctor_remove_staff_primary_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='number_of_patients',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
