# Generated by Django 6.0.1 on 2026-04-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_staff_number_of_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='number_of_patients',
            field=models.IntegerField(default=0),
        ),
    ]
